use nncloud;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE activation_functions;
TRUNCATE TABLE synapses;
TRUNCATE TABLE neurons;
TRUNCATE TABLE layers;  
TRUNCATE TABLE networks;
SET FOREIGN_KEY_CHECKS = 1;
